[package]
name = "sekursranko"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[dependencies]
futures = "0.1"
hyper = "0.12"
log = "0.4"
route-recognizer = "0.1"
serde = "1.0"
serde_derive = "*"
serde_json = "1.0"

[dev-dependencies]
reqwest = "*"
